### PR TITLE
Removing first REPL and removed arguement from Main

### PR DESCRIPTION
**Pull request by efleming18**

### CODE REVIEW

**Comment by ardalis** [comment]
If you have code listings that shouldn't run in the REPL, just use the ```c# syntax rather than snippet.

If it's not important for the user to see the code to populate sample data, you can just put that code in the REPL block (down at the bottom of the code listing). Is that what you're trying to do? I'm not clear why you're deleting the code that populates your data.

**Comment by ardalis** [comment]
:watch:

**Comment by efleming18** [comment]
@ardalis The big piece I removed shouldn't run, so I'll change it to the ```c# syntax. It just my "overview" of the code they will be using throughout.

**Comment by efleming18** [comment]
@ardalis Ready

**Comment by ardalis** [comment]
:shipit:

**Pull request merged**
