### PR TITLE
Create strings.md

### PR DESCRIPTION
**Pull request by badersur**

### CODE REVIEW

**Comment by badersur** [comment]
Change **than** to **that** in the sentence below. I thought it's clear so I didn't leave an explanation! sorry about this.

> For a little extra credit, support an optional third variable **than** can be set to either 'loud' or 'quiet'.

**Comment by ardalis** [comment]
Ah, perfect, thanks. I didn't see that difference in the online diff tool.

**Comment by ardalis** [comment]
Thanks!

**Comment by badersur** [comment]
You're welcome :)
I noticed it's not clear so I should learn to explain my changes from now on!

I also think this was one of the reasons to file the old issue: #168

**Pull request merged**
